### PR TITLE
Install semantic ui and fix sign out icon in index.html

### PR DESCRIPTION
**Pull request by djonvincent**

### CODE REVIEW

**Comment by agentreno** [comment]
Your commit removes logs/site.log rather than just ignoring changes to it. I just cloned your repo and tried to run the server, but without this log file it produces an error.

**Comment by djonvincent** [comment]
I didn't realise I was removing that file, I'll add it back

**Comment by agentreno** [comment]
Cool - unfortunately we have another problem with this, the navbar links don't appear to be working? I don't see the d3js visualisation and the URL isn't changing?

**Comment by agentreno** [comment]
Never mind, this seems to be an intermittent problem probably not caused by your code. Merging.

**Pull request merged**
